services:
  postgres: 
    hostname: ${POSTGRES_HOST}
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
    ports:
      - ${POSTGRES_PORT}:5432

  api:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - ${API_PORT}:${API_PORT}

volumes:
  pgdata:

networks:
  backend:
    name: ${NETWORK_NAME}