services:
  postgres: 
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  api:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    env_file:
      - .env
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
